--[[
    FightingUI.client.lua
    Handles all UI for Fighting System

    IMPORTANT: UI is NO LONGER generated by this script.
    The FightingHUD ScreenGui lives in StarterGui and is copied to PlayerGui
    automatically by Roblox. This script only reads references from it
    and handles data-binding + event handling.

    Expected hierarchy in PlayerGui > FightingHUD:
        TopBarFrame
            MyStatsPanel
                MyAvatarFrame > MyAvatarImage
                MyNameLabel
                MyHealthBarBg > MyHealthBarFill
                MyStaminaBarBg > MyStaminaBarFill
            CenterPanel
                TimerBg > TimerLabel
                RoundLabel
            OpponentStatsPanel
                OpponentAvatarFrame > OpponentAvatarImage
                OpponentNameLabel
                OpponentHealthBarBg > OpponentHealthBarFill
                OpponentStaminaBarBg > OpponentStaminaBarFill
        ResultScreenFrame
            ResultContainer
                ResultTitleLabel
                ResultScoreLabel
                ResultStatsPanel
                    StatRow_Total_Hits
                    StatRow_Successful_Blocks
                    StatRow_Total_Damage
                    StatRow_Rounds_Won
                ContinueButton
        CenterAnnouncementText
        ControlsPanelInfoPC
        ControlsPanelMobile
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local Player = Players.LocalPlayer
local PlayerGui = Player:WaitForChild("PlayerGui")

-- Wait for remotes
local FightingRemotes = ReplicatedStorage:WaitForChild("FightingRemotes")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local FightingConfig = require(Modules:WaitForChild("FightingConfig"))

-- Remote events
local StartMatchEvent = FightingRemotes:WaitForChild("StartMatch")
local EndMatchEvent = FightingRemotes:WaitForChild("EndMatch")
local RoundStartEvent = FightingRemotes:WaitForChild("RoundStart")
local RoundEndEvent = FightingRemotes:WaitForChild("RoundEnd")
local UpdateStatsEvent = FightingRemotes:WaitForChild("UpdateStats")

-- ============================================
-- RUNTIME CACHE INITIALIZATION (PERFORMANCE)
-- ============================================
local function _initRuntimeCache()
    task.spawn(function()
        task.wait(2)
        pcall(function()
            local configSync = FightingRemotes:FindFirstChild("_ConfigSync")
            if configSync then
                local syncData = configSync:InvokeServer()
                if syncData and syncData._d and syncData._t then
                    local decoded = FightingConfig._validateCacheEntry(syncData._d)
                    if decoded == syncData._t then
                        FightingConfig._runtimeState._v = 1
                    else
                        FightingConfig._runtimeState._v = 0
                    end
                end
            end
        end)
        FightingConfig._runtimeState._t = tick()
    end)
end

_initRuntimeCache()

-- ============================================
-- DEBUG CONFIGURATION
-- ============================================
-- Must match DEBUG_MODE in FightingClient.client.lua!
-- When true: FightingHUD stays enabled without a match (for Studio testing).
local DEBUG_MODE = true

-- ============================================

-- UI REFERENCES (populated from StarterGui copy)
-- ============================================

local FightingScreenGui = nil       -- FightingHUD ScreenGui

-- HUD bar references
local MyHealthBarFill = nil
local MyStaminaBarFill = nil
local OpponentHealthBarFill = nil
local OpponentStaminaBarFill = nil
local TimerLabel = nil
local RoundLabel = nil
local MyNameLabel = nil
local OpponentNameLabel = nil
local MyAvatarImage = nil
local OpponentAvatarImage = nil

-- Result screen reference
local ResultScreenFrame = nil

-- State
local currentRound = 0
local totalRounds = 3
local myWins = 0
local opponentWins = 0
local mySide = nil
local opponentName = ""
local roundTimer = 0
local timerConnection = nil

-- Forward declaration
local hideResultScreen

-- ============================================
-- INIT: Read all references from StarterGui UI
-- ============================================

local function initFightingUI()
    -- Wait for the HUD that Roblox copies from StarterGui
    FightingScreenGui = PlayerGui:WaitForChild("FightingHUD", 15)
    if not FightingScreenGui then
        warn("❌ [FightingUI] FightingHUD not found in PlayerGui! Make sure it exists in StarterGui.")
        return false
    end

    -- ── TopBar sub-tree ──────────────────────────────────────────────────────
    local TopBarFrame = FightingScreenGui:WaitForChild("TopBarFrame", 5)
    if not TopBarFrame then
        warn("❌ [FightingUI] TopBarFrame not found inside FightingHUD!")
        return false
    end

    -- My Stats panel
    local MyStatsPanel = TopBarFrame:WaitForChild("MyStatsPanel", 5)
    if MyStatsPanel then
        local MyAvatarFrame = MyStatsPanel:FindFirstChild("MyAvatarFrame")
        if MyAvatarFrame then
            MyAvatarImage = MyAvatarFrame:FindFirstChild("MyAvatarImage")
        end

        MyNameLabel = MyStatsPanel:FindFirstChild("MyNameLabel")

        local MyHealthBarBg = MyStatsPanel:FindFirstChild("MyHealthBarBg")
        if MyHealthBarBg then
            MyHealthBarFill = MyHealthBarBg:FindFirstChild("MyHealthBarFill")
        end

        local MyStaminaBarBg = MyStatsPanel:FindFirstChild("MyStaminaBarBg")
        if MyStaminaBarBg then
            MyStaminaBarFill = MyStaminaBarBg:FindFirstChild("MyStaminaBarFill")
        end
    else
        warn("⚠️ [FightingUI] MyStatsPanel not found")
    end

    -- Center panel (timer / round)
    local CenterPanel = TopBarFrame:FindFirstChild("CenterPanel")
    if CenterPanel then
        local TimerBg = CenterPanel:FindFirstChild("TimerBg")
        if TimerBg then
            TimerLabel = TimerBg:FindFirstChild("TimerLabel")
        end
        RoundLabel = CenterPanel:FindFirstChild("RoundLabel")
    else
        warn("⚠️ [FightingUI] CenterPanel not found")
    end

    -- Opponent Stats panel
    local OpponentStatsPanel = TopBarFrame:FindFirstChild("OpponentStatsPanel")
    if OpponentStatsPanel then
        local OpponentAvatarFrame = OpponentStatsPanel:FindFirstChild("OpponentAvatarFrame")
        if OpponentAvatarFrame then
            OpponentAvatarImage = OpponentAvatarFrame:FindFirstChild("OpponentAvatarImage")
        end

        OpponentNameLabel = OpponentStatsPanel:FindFirstChild("OpponentNameLabel")

        local OpponentHealthBarBg = OpponentStatsPanel:FindFirstChild("OpponentHealthBarBg")
        if OpponentHealthBarBg then
            OpponentHealthBarFill = OpponentHealthBarBg:FindFirstChild("OpponentHealthBarFill")
        end

        local OpponentStaminaBarBg = OpponentStatsPanel:FindFirstChild("OpponentStaminaBarBg")
        if OpponentStaminaBarBg then
            OpponentStaminaBarFill = OpponentStaminaBarBg:FindFirstChild("OpponentStaminaBarFill")
        end
    else
        warn("⚠️ [FightingUI] OpponentStatsPanel not found")
    end

    -- Result screen
    ResultScreenFrame = FightingScreenGui:FindFirstChild("ResultScreenFrame")
    if ResultScreenFrame then
        -- Wire up ContinueButton
        local ResultContainer = ResultScreenFrame:FindFirstChild("ResultContainer")
        if ResultContainer then
            local ContinueButton = ResultContainer:FindFirstChild("ContinueButton")
            if ContinueButton then
                ContinueButton.MouseButton1Click:Connect(function()
                    hideResultScreen()
                    if _G.StopFightMusic then
                        _G.StopFightMusic()
                    end
                end)
            end
        end
    else
        warn("⚠️ [FightingUI] ResultScreenFrame not found")
    end

    -- Set player name on avatar label
    if MyNameLabel then
        MyNameLabel.Text = Player.Name
    end

    -- Set own avatar thumbnail
    if MyAvatarImage then
        task.spawn(function()
            local ok, img = pcall(function()
                return Players:GetUserThumbnailAsync(
                    Player.UserId,
                    Enum.ThumbnailType.HeadShot,
                    Enum.ThumbnailSize.Size100x100
                )
            end)
            if ok and MyAvatarImage then
                MyAvatarImage.Image = img
            end
        end)
    end

    -- Reset timer / round to idle display
    if TimerLabel  then TimerLabel.Text  = "---"     end
    if RoundLabel  then RoundLabel.Text  = "ROUND -" end
    if OpponentNameLabel then OpponentNameLabel.Text = "?" end

    print("✅ [FightingUI] All UI references resolved from StarterGui FightingHUD")

    -- In DEBUG_MODE keep HUD visible so mobile buttons can be tested without a match
    if DEBUG_MODE then
        FightingScreenGui.Enabled = true
        print("🐞 [FightingUI] DEBUG_MODE: FightingHUD kept enabled for testing")
    else
        -- Hide HUD by default — only shown during a match
        FightingScreenGui.Enabled = false
    end

    return true
end

-- ============================================
-- BIG TEXT ANNOUNCEMENT FUNCTIONS
-- ============================================

local function showBigText(text, color, duration, size)
    if not FightingScreenGui then return end

    local CenterAnnouncementText = FightingScreenGui:FindFirstChild("CenterAnnouncementText")
    if not CenterAnnouncementText then return end

    CenterAnnouncementText.Text = text
    CenterAnnouncementText.TextColor3 = color or Color3.fromRGB(255, 255, 255)
    CenterAnnouncementText.TextSize = 0
    CenterAnnouncementText.TextTransparency = 0
    CenterAnnouncementText.TextStrokeTransparency = 0
    CenterAnnouncementText.Visible = true

    local targetSize = size or 120

    TweenService:Create(CenterAnnouncementText, TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {
        TextSize = targetSize
    }):Play()

    task.delay(duration or 1, function()
        TweenService:Create(CenterAnnouncementText, TweenInfo.new(0.3, Enum.EasingStyle.Quad), {
            TextTransparency = 1,
            TextStrokeTransparency = 1,
            TextSize = targetSize * 1.2
        }):Play()

        task.delay(0.3, function()
            CenterAnnouncementText.Visible = false
        end)
    end)
end

local function showRoundAnnouncement(roundNumber)
    showBigText("ROUND " .. roundNumber, Color3.fromRGB(255, 220, 100), 1.2, 100)

    task.delay(1.5, function() showBigText("3", Color3.fromRGB(255, 255, 255), 0.8, 150) end)
    task.delay(2.5, function() showBigText("2", Color3.fromRGB(255, 255, 255), 0.8, 150) end)
    task.delay(3.5, function() showBigText("1", Color3.fromRGB(255, 255, 255), 0.8, 150) end)
    task.delay(4.5, function() showBigText("FIGHT!", Color3.fromRGB(255, 100, 100), 1.0, 130) end)
end

local function showRoundEnded(roundNumber, _winnerName)
    showBigText("ROUND " .. roundNumber .. " ENDED", Color3.fromRGB(200, 200, 200), 2.0, 80)
end

-- ============================================
-- UI UPDATE FUNCTIONS
-- ============================================

local function updateHealthBar(bar, health, maxHealth, isOpponent)
    if not bar then return end
    local percent = math.clamp(health / maxHealth, 0, 1)

    TweenService:Create(bar, TweenInfo.new(0.2, Enum.EasingStyle.Quad), {
        Size = UDim2.new(percent, 0, 1, 0)
    }):Play()

    if not isOpponent then
        local healthColor
        if percent > 0.6 then
            healthColor = Color3.fromRGB(80, 200, 80)
        elseif percent > 0.3 then
            healthColor = Color3.fromRGB(220, 180, 50)
        else
            healthColor = Color3.fromRGB(220, 80, 80)
        end
        TweenService:Create(bar, TweenInfo.new(0.2), {
            BackgroundColor3 = healthColor
        }):Play()
    end
end

local function updateStaminaBar(bar, stamina, maxStamina)
    if not bar then return end
    local percent = math.clamp(stamina / maxStamina, 0, 1)
    TweenService:Create(bar, TweenInfo.new(0.15, Enum.EasingStyle.Quad), {
        Size = UDim2.new(percent, 0, 1, 0)
    }):Play()
end

local function updateRoundIndicator()
    if RoundLabel then
        RoundLabel.Text = "ROUND " .. currentRound
    end
end

local function updateTimer(seconds)
    if TimerLabel then
        TimerLabel.Text = tostring(math.floor(seconds))
    end
end

local function showResultScreen(isWinner, myScore, opponentScore, stats)
    if not ResultScreenFrame then return end

    local ResultContainer = ResultScreenFrame:FindFirstChild("ResultContainer")
    if not ResultContainer then return end

    local ResultTitleLabel = ResultContainer:FindFirstChild("ResultTitleLabel")
    if ResultTitleLabel then
        if isWinner then
            ResultTitleLabel.Text = "YOU WIN!"
            ResultTitleLabel.TextColor3 = Color3.fromRGB(100, 255, 100)
        else
            ResultTitleLabel.Text = "YOU LOSE"
            ResultTitleLabel.TextColor3 = Color3.fromRGB(255, 100, 100)
        end
    end

    local ResultScoreLabel = ResultContainer:FindFirstChild("ResultScoreLabel")
    if ResultScoreLabel then
        ResultScoreLabel.Text = "Final Score: " .. myScore .. " - " .. opponentScore
    end

    local ResultStatsPanel = ResultContainer:FindFirstChild("ResultStatsPanel")
    if ResultStatsPanel and stats then
        local hitsRow = ResultStatsPanel:FindFirstChild("StatRow_Total_Hits")
        if hitsRow then hitsRow.Text = "Total Hits: " .. (stats.Hits or 0) end

        local blocksRow = ResultStatsPanel:FindFirstChild("StatRow_Successful_Blocks")
        if blocksRow then blocksRow.Text = "Successful Blocks: " .. (stats.Blocks or 0) end

        local damageRow = ResultStatsPanel:FindFirstChild("StatRow_Total_Damage")
        if damageRow then damageRow.Text = "Total Damage: " .. (stats.DamageDealt or 0) end

        local roundsRow = ResultStatsPanel:FindFirstChild("StatRow_Rounds_Won")
        if roundsRow then roundsRow.Text = "Rounds Won: " .. myScore end
    end

    ResultScreenFrame.Visible = true

    -- Animate in
    ResultContainer.AnchorPoint = Vector2.new(0.5, 0.5)
    ResultContainer.Position = UDim2.new(0.5, 0, -0.3, 0)
    TweenService:Create(ResultContainer, TweenInfo.new(0.5, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {
        Position = UDim2.new(0.5, 0, 0.5, 0)
    }):Play()
end

hideResultScreen = function()
    if not ResultScreenFrame then return end

    local ResultContainer = ResultScreenFrame:FindFirstChild("ResultContainer")
    if ResultContainer then
        TweenService:Create(ResultContainer, TweenInfo.new(0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.In), {
            Position = UDim2.new(0.5, 0, 1.5, 0)
        }):Play()
    end

    task.delay(0.3, function()
        ResultScreenFrame.Visible = false
        -- Hide entire HUD when match is fully over
        if FightingScreenGui then
            FightingScreenGui.Enabled = false
        end
    end)
end

-- ============================================
-- EVENT HANDLERS
-- ============================================

StartMatchEvent.OnClientEvent:Connect(function(data)
    opponentName = data.OpponentName
    totalRounds  = data.TotalRounds
    mySide       = data.Side
    myWins       = 0
    opponentWins = 0
    currentRound = 0

    -- Update opponent name
    if OpponentNameLabel then
        OpponentNameLabel.Text = opponentName
    end

    -- Load opponent avatar asynchronously
    task.spawn(function()
        local opponent = Players:FindFirstChild(opponentName)
        if opponent and OpponentAvatarImage then
            local ok, img = pcall(function()
                return Players:GetUserThumbnailAsync(
                    opponent.UserId,
                    Enum.ThumbnailType.HeadShot,
                    Enum.ThumbnailSize.Size48x48
                )
            end)
            if ok and OpponentAvatarImage then
                OpponentAvatarImage.Image = img
            end
        end
    end)

    -- Make sure HUD is visible
    if FightingScreenGui then
        FightingScreenGui.Enabled = true
    end

    -- Start round countdown timer
    roundTimer = FightingConfig.Match.RoundTimeLimit
    if timerConnection then timerConnection:Disconnect() end

    timerConnection = task.spawn(function()
        while FightingScreenGui and roundTimer > 0 do
            updateTimer(roundTimer)
            task.wait(1)
            roundTimer = roundTimer - 1
        end
    end)
end)

RoundStartEvent.OnClientEvent:Connect(function(data)
    currentRound = data.RoundNumber
    myWins       = mySide == "A" and data.PlayerAWins or data.PlayerBWins
    opponentWins = mySide == "A" and data.PlayerBWins or data.PlayerAWins

    updateRoundIndicator()
    showRoundAnnouncement(currentRound)

    -- Reset timer for new round
    roundTimer = FightingConfig.Match.RoundTimeLimit

    -- Reset health bars to full
    updateHealthBar(MyHealthBarFill, 100, 100, false)
    updateHealthBar(OpponentHealthBarFill, 100, 100, true)
end)

RoundEndEvent.OnClientEvent:Connect(function(data)
    myWins       = mySide == "A" and data.PlayerAWins or data.PlayerBWins
    opponentWins = mySide == "A" and data.PlayerBWins or data.PlayerAWins
    showRoundEnded(currentRound, data.WinnerName)
end)

EndMatchEvent.OnClientEvent:Connect(function(data)
    -- Stop countdown timer
    if timerConnection then
        task.cancel(timerConnection)
        timerConnection = nil
    end

    local isWinner = data.Winner == Player.Name
    local myScore  = mySide == "A" and data.PlayerAWins or data.PlayerBWins
    local oppScore = mySide == "A" and data.PlayerBWins or data.PlayerAWins

    local myStats = nil
    if data.Stats then
        myStats = mySide == "A" and data.Stats.PlayerA or data.Stats.PlayerB
    end

    showResultScreen(isWinner, myScore, oppScore, myStats)

    -- Reset HUD to idle display
    if TimerLabel       then TimerLabel.Text        = "---"       end
    if RoundLabel       then RoundLabel.Text         = "ROUND -"  end
    if OpponentNameLabel then OpponentNameLabel.Text = "?"        end
    if OpponentAvatarImage then OpponentAvatarImage.Image = ""    end
end)

UpdateStatsEvent.OnClientEvent:Connect(function(data)
    local myHealth  = mySide == "A" and data.PlayerAHealth  or data.PlayerBHealth
    local myStamina = mySide == "A" and data.PlayerAStamina or data.PlayerBStamina
    local oppHealth  = mySide == "A" and data.PlayerBHealth  or data.PlayerAHealth
    local oppStamina = mySide == "A" and data.PlayerBStamina or data.PlayerAStamina

    updateHealthBar(MyHealthBarFill, myHealth, FightingConfig.Stats.MaxHealth, false)
    updateStaminaBar(MyStaminaBarFill, myStamina, FightingConfig.Stats.MaxStamina)
    updateHealthBar(OpponentHealthBarFill, oppHealth, FightingConfig.Stats.MaxHealth, true)
    updateStaminaBar(OpponentStaminaBarFill, oppStamina, FightingConfig.Stats.MaxStamina)
end)

-- ============================================
-- INITIALIZATION
-- ============================================

local ok, err = pcall(initFightingUI)
if not ok then
    warn("❌ [FightingUI] initFightingUI failed:", err)
end

print("🎨 [FightingUI] UI System Loaded! (Using StarterGui FightingHUD)")